<section class="row">
  <h1>Éditer le profil du chat: <?= $data[0]['cat']->getName(); ?></h1>
  <form method="post" class="col">
    <div class="mb-3">
      <label for="cat-name" class="form-label">Nom:</label>
      <input type="text" class="form-control" id="cat-name" name="cat-name" value="<?= $data[0]['cat']->getName(); ?>">
    </div>
    <div class="mb-3">
      <label for="cat-age" class="form-label">Âge</label>
      <input type="text" class="form-control" id="cat-age" name="cat-age" value="<?= $data[0]['cat']->getAge(); ?>">
    </div>
    <div class="mb-3">
      <select class="form-select" aria-label="Default select example" id="cat-sex" name="cat-sex">
        <?php if($data[0]['cat']->getSex() === "mâle"){ ?>
          <option value="">Sexe</option>
          <option value="mâle" selected="selected">mâle</option>
          <option value="femelle">femelle</option>
        <?php }else{ ?>
          <option value="">Sexe</option>
          <option value="mâle">mâle</option>
          <option value="femelle" selected="selected">femelle</option>
        <?php } ?>
      </select>
    </div>
    <div class="mb-3">
      <label for="cat-color" class="form-label">Couleur:</label>
      <input type="text" class="form-control" id="cat-color" name="cat-color" value="<?= $data[0]['cat']->getColor(); ?>">
    </div>
    <div class="mb-3">
      <label for="cat-description" class="form-label">Détails:</label>
      <textarea type="text" class="form-control" id="cat-description" name="cat-description"><?= $data[0]['cat']->getDescription(); ?></textarea>
    </div>
    <div class="mb-3 form-check">
        <?php if($data[0]['cat']->getIsSterilized() === "oui"){ ?>
            <input type="checkbox" class="form-check-input" id="cat-is-sterilized" name="cat-is-sterilized" checked>
        <?php }else{ ?>
            <input type="checkbox" class="form-check-input" id="cat-is-sterilized" name="cat-is-sterilized">
        <?php } ?>
        <label class="form-check-label" for="cat-is-sterilized">Stérilisé</label>
    </div>
    <div class="mb-3">
      <select class="form-select" aria-label="Default select example" id="cat-family" name="cat-family">
          <option selected>Famille d'accueil</option>
          <?php foreach($data[1] as $family){ ?>
            <option value="<?= $family->getName() ?>" <?php if($family->getName() === $data[0]['cat']->getFamilyName()){ echo "selected"; }?>><?= $family->getName() ?></option>
          <?php } ?>
      </select>
    </div>
    <button type="submit" class="btn btn-success">Enregistrer</button>
    <a href="/res03-projet-final/admin/index-des-chats-a-l-adoption" type="submit" class="btn btn-primary">retour</a>
  </form>
  <div class="col">
    <figure>
      <img src="/res03-projet-final/assets/medias/images/cat-flowers.jpg" alt="Des mains tenant un chaton blanc avec un collier de fleurs" class="img-fluid">
      <figcaption class="d-none">Photo by Peng Louis on pexels.com</figcaption>
    </figure>
  </div>
</section>