<?php var_dump($data) ?>
<section>
  <h1>Les chats à l'adoption</h1>
  <a href="/res03-projet-final/admin/index-des-chats-a-l-adoption/creer" type="button" class="btn btn-success">Ajouter un chat à l'index</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nom</th>
        <th scope="col">Âge</th>
        <th scope="col">Sexe</th>
        <th scope="col">Couleur</th>
        <th scope="col">Sterilisé</th>
        <th scope="col">Famille</th>
        <th scope="col">Modifier</th>
      </tr>
    </thead>
    <tbody>
    <?php if(!empty($data)){ foreach($data as $cat){ ?>
      <tr>
        <th scope="row"><?= strval($cat->getId()); ?></th>
        <td><?= $cat->getName(); ?></td>
        <td><?= $cat->getAge(); ?></td>
        <td><?= $cat->getSex(); ?></td>
        <td><?= $cat->getColor(); ?></td>
        <td><?= $cat->getIsSterilized(); ?></td>
        <td><?= $cat->getFamilyName(); ?></td>
        <td>
          <a class="btn btn-info" href="/res03-projet-final/admin/index-des-chats-a-l-adoption/<?= $cat->getId(); ?>/voir" role="button">Détails</a>
          <a class="btn btn-primary" href="/res03-projet-final/admin/index-des-chats-a-l-adoption/<?= $cat->getId(); ?>/editer" role="button">Éditer</a>
          <a class="btn btn-danger" href="/res03-projet-final/admin/index-des-chats-a-l-adoption/<?= $cat->getId(); ?>/supprimer" role="button">Supprimer</a>
        </td>
      </tr>
      <?php }} ?>
    </tbody>
  </table>
</section>