<h1>This is the cat create form</h1>
<form method="post">
  <div class="mb-3">
    <label for="cat-name" class="form-label">Nom:</label>
    <input type="text" class="form-control" id="cat-name">
  </div>
  <div class="mb-3">
    <label for="cat-age" class="form-label">Âge</label>
    <input type="text" class="form-control" id="cat-age">
  </div>
  <div class="mb-3">
    <select class="form-select" aria-label="Default select example">
        <option selected>Sexe</option>
        <option value="1">Mâle</option>
        <option value="2">Femelle</option>
    </select>
  </div>
  <div class="mb-3">
    <label for="cat-color" class="form-label">Couleur:</label>
    <input type="text" class="form-control" id="cat-color">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="is-sterilized">
    <label class="form-check-label" for="is-sterilized">Stérilisé</label>
  </div>
  <div class="mb-3">
    <select class="form-select" aria-label="Default select example">
        <option selected>Famille d'accueil</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>