<section>
  <h1>Index des articles du blog</h1>
  <a href="/res03-projet-final/admin/index-des-articles/creer" type="button" class="btn btn-success">Ajouter un article au blog</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre</th>
        <th scope="col">Contenu</th>
        <th scope="col">Auteur-ice</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
      <?php if(!empty($data)){ foreach($data[0] as $post){ ?>
      <tr>
        <th scope="row"><?= strval($post['id']); ?></th>
        <td><?= $post['title']; ?></td>
        <td><?= $post['content']; ?></td>
        <td><?= $post['author']; ?></td>
        <td><?= $post['date']; ?></td>
      </tr>
      <?php }} ?>
    </tbody>
  </table>
</section>
