<footer>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin">Accueil</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin/index-des-chats-a-l-adoption">Les chats</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin/les-utilisateurs">Les utilisateurs</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin/les-familles">Les familles</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin/les-evenements">Les évènements</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin/les-articles">Les articles</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/res03-projet-final/admin/les-maladies">Les maladies</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>
</footer>