<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final">Homeless Kitten Association</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin">Admin</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/index-des-chats-a-l-adoption">Les chats</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link <?= $logInfos['displayLinkForAdminOnly'] ?>" href="/res03-projet-final/admin/index-des-utilisateurs">Les utilisateurs</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link <?= $logInfos['displayLinkForAdminOnly'] ?>" href="/res03-projet-final/admin/index-des-familles">Les familles</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link <?= $logInfos['displayLinkForAdminOnly'] ?>" href="/res03-projet-final/admin/index-des-evenements">Les évènements</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= $logInfos['displayLinkForAdminOnly'] ?>" href="/res03-projet-final/admin/index-des-maladies">Les maladies</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/index-des-articles">Les articles</a>
                    </li>
                    <li class="nav-item">
                    <a href="<?= $logInfos['logLink'] ?>" class="nav-link"><?= $logInfos['logLinkText'] ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>