<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="">Accueil</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="a-l-adoption">Les chats</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="utilisateurs">Les utilisateurs</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="familles">Les familles</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="evenements">Les évènements</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="blog">Les articles</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>
    <!-- <h2 class="sr-only"></h2>
    <nav>
        <h2 class="sr-only">Header-navigation</h2>
        <ul>
            <li></li>
            <li><a href="index.php?route=user-create">Créer un utilisateur</a></li>
            <li><a href="index.php?route=user-edit">Éditer un utilisateur</a></li>
        </ul>
    </nav> -->
</header>