<div class="borderUnderHeaderDecorationLine">
    <div class="underHeaderDecoration"></div>
</div>
<h2 class="sr-only">Faire un don à l'association</h2>  
<section class="hka-main-content-section">
    <h3>Faire un don à l'association</h3>
    <ul>
        <li><span class="fa-brands fa-cc-paypal"></span><a href="https://www.paypal.com/paypalme/HomelessKittenAsso?fbclid=IwAR0AZtotgcmAbTlZyY0D1U5T0tLIqsGjRlWliqZCRXwvfLcYkpB-ZviqAEc" target="_blank">Paypal</a></li>
        <li><span class="fa-solid fa-euro-sign"></span><a href="https://www.teaming.net/homelesskitten" target="_blank">Teaming</a></li>
        <li><span class="fa-solid fa-money-check"></span><a href="https://www.homelesskittenassociation.com/_files/ugd/5c7aa0_0571250fcf434e36811375d6c746f073.pdf" target="_blank">Virement bancaire</a></li>
    </ul> 
</section>