<div class="borderUnderHeaderDecorationLine">
    <div class="underHeaderDecoration"></div>
</div>
<section class="hka-main-content-section">
    <div class="outterBorderDecoration">
        <div class="innerBorderDecoration">
            <section id="hka-about-content-section">
                <header>
                    <h2>Une association qui a du chat !</h2>
                </header>
                <section>
                    <h3>Avoir un réel impact</h3>
                    <p>Nos actions ne peuvent prospérer qu'avec l'aide de familles d'accueil, prêtes à mettre à l'abri les chats que nous prenons en charge.
                    Être famille d'accueil est un réel engagement auprès d'eux et auprès de l'association qui permet de sauver de nombreuses vies. C'est une magnifique aventure qui apporte son lot d'émotions et d'investissement, et dont la satisfaction et la solidarité résultent.</p>
                    <p>Le matériel, l'alimentation et les frais vétérinaires sont évidemment à la charge de l'association. Qu'attendez-vous ?</p>
                    <a href="/res03-projet-final/familles">Nos familles d'accueil</a>
                </section>
                <footer>
                    <p>N'hésitez plus à nous rejoindre !</p>
                    <a href="/res03-projet-final/contact">Contacter</a>
                </footer>
            </section>
        </div>
    </div>
</section>