<div class="borderUnderHeaderDecorationLine">
    <div class="underHeaderDecoration"></div>
</div>
<section class="hka-main-content-section">
    <h2 class="sr-only">404 : page not found</h2>
    <h3>CAT SANS CAT !</h3>
    <section class="hka-404-content-section">
        <span class="fa-solid fa-cat hka-404-cat-span"></span>
        <span class="fa-solid fa-question hka-404-question-span"></span>
        <span class="fa-solid fa-question hka-404-question-span"></span>
        <span class="fa-solid fa-question hka-404-question-span"></span>
        <a href="/res03-projet-final/">Par ici les minous !</a>
    </section>
</section>