<section class="row">
  <h1>Éditer la maladie: <?= $data['disease']->getName() ?></h1>
  <form method="post" class="col">
    <div class="mb-3">
      <label for="disease-name" class="form-label">Nom:</label>
      <input type="text" class="form-control" id="disease-name" name="disease-name" value="<?= $data['disease']->getName() ?>">
    </div>
    <div class="mb-3">
      <label for="disease-description" class="form-label">Description:</label>
      <textarea type="text" class="form-control" id="disease-description" name="disease-description" style="height: 35vh;"><?= $data['disease']->getDescription() ?></textarea>
    </div>
    <div class="mb-3">
      <label for="disease-treatment" class="form-label">Traitement:</label>
      <textarea type="text" class="form-control" id="disease-treatment" name="disease-treatment" style="height: 35vh;"><?= $data['disease']->getTreatment() ?></textarea>
    </div>
    <button type="submit" class="btn btn-success">Enregistrer</button>
    <a href="/res03-projet-final/admin/index-des-maladies" type="submit" class="btn btn-primary">Retour</a>
  </form>
  <div class="col">
    <figure>
      <img src="/res03-projet-final/assets/medias/images/virus.jpg" alt="Tir microscopique d'un virus" class="img-fluid">
      <figcaption class="d-none">Photo by CDC on pexels.com</figcaption>
    </figure>
  </div>
</section>

