<section class="row container-fluid">
    <h1 class="mb-5">La fiche détaillée de l'évènement <?= $data[0]['event']->getName() ?></h1>
    <section class="col">
        <h2 class="d-none">photo de l'évènement <?= $data[0]['event']->getName() ?></h2>
        <figure>
            <?php if(($data[0]['event']->getMediaId()) === null){ ?>
                    <img style="max-height: 30vh;" class="img-thumbnail img-fluid" src="/res03-projet-final/assets/medias/images/cat-yawning.jpg" alt="">
                    <figcaption class="d-none">Une photo de chat qui miaule</figcaption>
                <?php }else{ ?>
                    <img style="max-height: 30vh;" class="img-thumbnail img-fluid" src="/res03-projet-final/<?= $data[1]->getUrl(); ?>" alt="">
                    <figcaption class="d-none">Une photo pour illustrer <?= $data[0]['event']->getName() ?></figcaption>
                <?php } ?>
        </figure>
    </section>
    <section class="col">
        <h2>évènement</h2>
        <ul class="list-group">
            <li class="list-group-item"><p><strong>Nom: </strong><?= $data[0]['event']->getName() ?></p></li>
            <li class="list-group-item"><p><strong>Description: </strong><?= $data[0]['event']->getDescription() ?></p></li>
            <li class="list-group-item"><p><strong>Lieu: </strong><?= $data[0]['event']->getLocation() ?></p></li>
            <li class="list-group-item"><p><strong>Date: </strong><?= $data[0]['event']->getDate() ?></p></li>
        </ul>
    </section>
</section>
<a href="/res03-projet-final/admin/index-des-evenements" type="submit" class="btn btn-primary m-3" style="width: fit-content;">retour</a>
<section class="row">
    <h2>Description et photos</h2>
    <section class="col">
        <h3 class="d-none">Description</h3>
        <p class="m-3"><?= $data[0]['event']->getDescription() ?></p>
    </section>
    <section class="row">
        <figure class="card-img-top card col-3" style="max-width: fit-content;">
            <img style="max-height: 25vh; aspect-ratio: keep-aspect-ratio;" class="img-thumbnail img-fluid card-img-top" src="/res03-projet-final/<?= $data[1]->getUrl(); ?>" alt="">
            <figcaption class="d-none">Une photo illustrant l'évènement <?= $data[0]['event']->getName() ?></figcaption>
            <div class="card-body">
                <a href="/res03-projet-final/admin/index-des-evenements/<?= $data[0]['event']->getId() ?>/editer" class="btn btn-primary">Éditer</a>
            </div>
        </figure>
    </section>
</section>