<section class="row">
  <h1>Ajouter un nouvel évènement à l'index</h1>
  <form method="post" class="col" enctype="multipart/form-data">
    <div class="mb-3">
      <label for="event-name" class="form-label">Nom:</label>
      <input type="text" class="form-control" id="event-name" name="event-name">
    </div>
    <div class="mb-3">
      <label for="event-description" class="form-label">Description:</label>
      <input type="text" class="form-control" id="event-description" name="event-description">
    </div>
    <div class="mb-3">
      <label for="event-location" class="form-label">Localisation:</label>
      <input type="text" class="form-control" id="event-location" name="event-location">
    </div>
    <div class="mb-3">
      <label for="event-date" class="form-label">Date:</label>
      <input type="date" class="form-control" id="event-date" name="event-date">
    </div>
    <div class="mb-3">
      <label for="event-medias" class="form-label">Sélectionnez une photo</label>
      <input class="form-control" type="file" id="event-medias" name="event-medias">
    </div>
    <button type="submit" class="btn btn-primary">Enregistrer</button>
    <a href="/res03-projet-final/admin/index-des-evenements" type="submit" class="btn btn-primary">Retour</a>
  </form>
  <div class="col">
    <figure>
      <img src="/res03-projet-final/assets/medias/images/feeding-cats.jpg" alt="Une femme nourrit des chats affamés" class="img-fluid">
      <figcaption class="d-none">Photo by NastyaSensei on pexels.com</figcaption>
    </figure>
  </div>
</section>

