<section>
  <h1>Index des utilisateurs</h1>
  <a href="/res03-projet-final/admin/index-des-utilisateurs/creer" type="button" class="btn btn-success">Ajouter un utilisateur à l'index</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Statut</th>
      </tr>
    </thead>
    <tbody>
    <?php if(!empty($data)){ foreach($data as $user){ ?>
      <tr>
        <th scope="row"><?= strval($user->getId()); ?></th>
        <td><?= $user->getFirstName(); ?></td>
        <td><?= $user->getLastName(); ?></td>
        <td><?= $user->getEMail(); ?></td>
        <td><?= $user->getRole(); ?></td>
        <td><?= $user->getStatus(); ?></td>
        <td>
          <a class="btn btn-info" href="/res03-projet-final/admin/index-des-utilisateurs/<?= $user->getId(); ?>/voir" role="button">Détails</a>
          <a class="btn btn-primary" href="/res03-projet-final/admin/index-des-utilisateurs/<?= $user->getId(); ?>/editer" role="button">Éditer</a>
          <a class="btn btn-danger" href="/res03-projet-final/admin/index-des-utilisateurs/<?= $user->getId(); ?>/supprimer" role="button">Supprimer</a>
        </td>
      </tr>
    <?php }} ?>
    </tbody>
  </table>
</section>
