<section>
  <h1>Index des utilisateurs</h1>
  <a href="/res03-projet-final/admin/index-des-utilisateurs/creer" type="button" class="btn btn-success">Ajouter un utilisateur à l'index</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Statut</th>
      </tr>
    </thead>
    <tbody>
    <?php if(!empty($data)){ foreach($data[0] as $user){ ?>
      <tr>
        <th scope="row"><?= strval($user['id']); ?></th>
        <td><?= $user['first_name']; ?></td>
        <td><?= $user['last_name']; ?></td>
        <td><?= $user['email']; ?></td>
        <td><?= $user['role']; ?></td>
        <td><?= $user['status']; ?></td>
      </tr>
    <?php }} ?>
    </tbody>
  </table>
</section>
