<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homeless Kitten Association</title>
</head>
<body>
    <header>
        <!-- <h2 class="sr-only"></h2>
        <nav>
            <h2 class="sr-only">Header-navigation</h2>
            <ul>
                <li><a href="index.php?route=">Accueil</a></li>
                <li><a href="index.php?route=user-create">Créer un utilisateur</a></li>
                <li><a href="index.php?route=user-edit">Éditer un utilisateur</a></li>
            </ul>
        </nav> -->
    </header>
    <main>
        
        <?php
            
        
            require $template."/".$template."_".$page.".phtml";
            
        ?>
    
    </main>
    <footer>
        <h2 class="sr-only"></h2>
        <nav>
            <h2 class="sr-only">Footer-navigation</h2>
            <ul>
                <li>Accueil</li>
                <li>Connexion</li>
                <li>Création de compte</li>
            </ul>
        </nav>
    </footer>
</body>
</html>
       