<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="Homeless Kitten Association">
    <meta name="description" content="Une association qui aide à accueillir les chats sans abris">
    <meta name="author" content="LeLwy">
    <meta name="referrer" content="LeLwy">
    <meta name="image" content="https://louischancioux.sites.3wa.io/res03-projet-final/assets/medias/images/logo.jpg">
    <meta property="og:title" content="Homeless Kitten Association">
    <meta property="og:description" content="Une association qui aide à accueillir les chats sans abris">
    <meta property="og:local" content="fr_FR">
    <meta property="og:image" content="https://louischancioux.sites.3wa.io/res03-projet-final/assets/medias/images/logo.jpg">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="https://louischancioux.sites.3wa.io/res03-projet-final/assets/styles/css/style.css">
    <title><?= $data[0]['title'] ?></title>
</head>
<body>

    <?php require 'header/_header.phtml'; ?>

    <main id="hka-page-<?= $data[0]['main_id'] ?>" class="hka-main-container">
        
        <?php
        
            require $template."/".$template."_".$page.".phtml";
            
        ?>
    
    </main>

    <?php require 'footer/_footer.phtml'; ?>
    <script type="application/javascript" src="https://louischancioux.sites.3wa.io/res03-projet-final/assets/js/index.js"></script> 
</body>
</html>
       