<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <title>Homeless Kitten Association</title>
</head>
<body>

    <?php require 'header/_header.phtml'; ?>

    <main>
        
        <?php
        
            require $template."/".$template."_".$page.".phtml";
            
        ?>
    
    </main>

    <?php require 'footer/_footer.phtml'; ?>
    
</body>
</html>
       