<section class="row">
  <h1>Ajouter une nouvelle famille à l'index</h1>
  <form method="post" class="col">
    <div class="mb-3">
      <label for="family-name" class="form-label">Nom:</label>
      <input type="text" class="form-control" id="family-name" name="family-name">
    </div>
    <div class="mb-3">
      <label for="family-description" class="form-label">Description:</label>
      <textarea type="text" class="form-control" id="family-description" name="family-description"></textarea>
    </div>
    <div class="mb-3">
      <label for="family-medias" class="form-label">Sélectionnez une photo</label>
      <input class="form-control" type="file" id="family-medias" name="family-medias">
    </div>
    <button type="submit" class="btn btn-primary">Enregistrer</button>
    <a href="/res03-projet-final/admin/index-des-familles" type="submit" class="btn btn-primary">Retour</a>
  </form>
  <div class="col">
    <figure>
      <img src="/res03-projet-final/assets/medias/images/cat-with-master.jpg" alt="Une femme tenant un chat contre elle" class="img-fluid">
      <figcaption class="d-none">Photo by Weitth on pexels.com</figcaption>
    </figure>
  </div>
</section>