<header>
    <h1 class="sr-only"><?= $data[0]['title'] ?></h1>
    <div id="burger-menu-cross" class="inactive burgerMenuElt"><span class="fa-solid fa-xmark"></span></div>
    <div id="burger-menu-bars" class="burgerMenuElt"><span class="fa-solid fa-bars"></span></div>
    <div id="logoMenu"><a href="/res03-projet-final/"><span class="fa-solid fa-shield-cat"></span></a></div>
    <nav id="header-navigation-menu">
        <h2 class="sr-only">Header-navigation</h2>
        <ul>
            <li class="headerLeftEltLi"><a href="/res03-projet-final/a-l-adoption"><span class="fa-solid fa-paw menuEltSpan"></span>À l'adoption</a></li>
            <li class="headerLeftEltLi"><a href="/res03-projet-final/a-propos"><span class="fa-solid fa-paw menuEltSpan"></span>L'association</a></li>
            <li class="headerLeftEltLi"><a href="/res03-projet-final/donation"><span class="fa-solid fa-paw menuEltSpan"></span>Dons</a></li>
            <li class="headerLogoEltLi" id="header-navigation-logo"><a href="/res03-projet-final/"><span class="fa-solid fa-shield-cat menuLogoSpan"></span></a></li>
            <li class="headerRightEltLi"><a href="/res03-projet-final/evenements"><span class="fa-solid fa-paw menuEltSpan"></span>Évènements</a></li>
            <li class="headerRightEltLi"><a href="/res03-projet-final/contact"><span class="fa-solid fa-paw menuEltSpan"></span>Nous contacter</a></li>
            <li class="headerRightEltLi"><a href="/res03-projet-final/blog"><span class="fa-solid fa-paw menuEltSpan"></span>Blog</a></li>
        </ul>
    </nav>
</header>